language: python

script:
  - pip install -r requirements.txt
  - python lint.py
deploy:
  provider: s3
  access_key_id: ACCESS_KEY
  secret_access_key:
    secure: ENCRYPTED_SECRET_KEY
  bucket: AWS_BUCKET_NAME
  local-dir: .
  skip_cleanup: true
  on:
    repo: DataBiosphere/example-authz-registry
    branch: master
